# Generated by Django 4.2.11 on 2024-05-02 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('shopping_cart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartitem',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='menu.product'),
            preserve_default=False,
        ),
    ]
