# Generated by Django 4.2.11 on 2024-05-02 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('shopping_cart', '0003_shoppingcartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='shoppingcartitem',
            name='meal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='menu.meal'),
            preserve_default=False,
        ),
    ]
