name: Django CI

on:
  push:
    branches: 
      - main
      - develop      
  pull_request:
    branches: [main]      

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag my-image-name:1234567890

    - name: Run Docker container
      run: docker run --name my-container -d -i -t -e DJANGO_SETTINGS_MODULE=restaurant.settings my-image-name:1234567890 /bin/sh

    - name: Run Django tests
      run: docker exec my-container python restaurant/manage.py test menu
           docker exec my-container python restaurant/manage.py test reservations
           


   
  merge:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && success()

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt-get update
        sudo apt-get install gh

    - name: Merge Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        gh pr merge $PR_NUMBER --merge --repo ${{ github.repository }} --delete-branch
